#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/gibstechjourney.blogspot.com permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
echo "server_tokens off;" | sudo tee -a /etc/nginx/nginx.conf
echo "more_set_headers 'X-Served-By: $HOSTNAME';" | sudo tee -a /etc/nginx/conf.d/custom.conf
sudo service nginx restart
