#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
i=0
while [[ "$i" -lt 10 ]]
do
	if [[ "$i" == 9 ]]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
