#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
#	display hours from 0 to 12
#	display minutes from 1 to 59
hours=0
while [[ "$hours" -le 12 ]]
do
	echo "Hour: $hours"
	minute=1
	while [[ "$minute" -le 59 ]]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hours++ ))
done
